/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulbra.br.view;

import java.awt.Color;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class SignosGabrielEGustavoNoite extends javax.swing.JFrame {

    /**
     * Creates new form SignosGabrielEGustavoNoite
     */
    public SignosGabrielEGustavoNoite() {
        initComponents();
        lbAries.setVisible(false);

        lbTouro.setVisible(false);

        lbCancer.setVisible(false);

        lbGemeos.setVisible(false);

        lbLeao.setVisible(false);

        lbVirgem.setVisible(false);

        lbLibra.setVisible(false);

        lbEscorpiao.setVisible(false);

        lbSagitario.setVisible(false);

        lbCapricornio.setVisible(false);

        lbAquario.setVisible(false);

        lbPeixes.setVisible(false);

    }

    public String calcularSigno(int dia, int mes, int ano) {

        String signo = "";
        if (dia >= 21 && dia <= 31 && mes == 3 || dia >= 1 && dia <= 20 && mes == 4) {

            signo = "Aries";
        }
        if (dia >= 21 && dia <= 30 && mes == 4 || dia >= 1 && dia <= 20 && mes == 5) {

            signo = "Touro";
        }
        if (dia >= 21 && dia <= 31 && mes == 5 || dia >= 1 && dia <= 20 && mes == 6) {

            signo = "Gêmeos";
        }
        if (dia >= 21 && dia <= 30 && mes == 6 || dia >= 1 && dia <= 21 && mes == 7) {

            signo = "Câncer";
        }
        if (dia >= 22 && dia <= 31 && mes == 7 || dia >= 1 && dia <= 22 && mes == 8) {

            signo = "Leão";
        }
        if (dia >= 23 && dia <= 30 && mes == 8 || dia >= 1 && dia <= 22 && mes == 9) {

            signo = "Virgem";
        }
        if (dia >= 23 && dia <= 31 && mes == 9 || dia >= 1 && dia <= 22 && mes == 10) {

            signo = "Libra";
        }
        if (dia >= 23 && dia <= 30 && mes == 10 || dia >= 1 && dia <= 21 && mes == 11) {

            signo = "Escorpião";
        }
        if (dia >= 22 && dia <= 31 && mes == 11 || dia >= 1 && dia <= 21 && mes == 12) {

            signo = "Sagitário";
        }
        if (dia >= 22 && dia <= 31 && mes == 12 || dia >= 1 && dia <= 20 && mes == 1) {

            signo = "Capricórnio";
        }
        if (dia >= 21 && dia <= 31 && mes == 1 || dia >= 1 && dia <= 19 && mes == 2) {

            signo = "Aquário";
        }
        if (dia >= 20 && dia <= 30 && mes == 2 || dia >= 1 && dia <= 20 && mes == 3) {

            signo = "Peixes";
        }

        return signo;
    }

    public String fazerTratamento(String tratamento1) {
        String tratamento = "";
        if (rbFem.isSelected()) {
            tratamento = "Sra";
        } else {
            tratamento = "Sr";
        }
        return tratamento;

    }

    public String declararCorDaSorte(String cor) {
        String corAleatoria[] = {"Azul", "Vermelho", "Amarelo", "Verde","Laranja","Marrom","Preto","Roxo","Rosa"};
        Random nCor = new Random();
        int i = nCor.nextInt(corAleatoria.length);
        String cores = corAleatoria[i];

        return cores;
    }

    public int calcularIdade(int dia, int mes, int ano) {
        LocalDate agr = LocalDate.now();
        int idade = 0;
        int diaAtual, mesAtual, anoAtual;
        diaAtual = agr.getDayOfMonth();
        mesAtual = agr.getMonthValue();
        anoAtual = agr.getYear();
        dia = Integer.parseInt(txtDia.getText());
        mes = Integer.parseInt(txtMes.getText());
        ano = Integer.parseInt(txtAno.getText());

        if (mes >= mesAtual) {

            idade = (anoAtual - ano - 1);
        } else {

            idade = anoAtual - ano;
        }
        return idade;
    }

    public int entregarNumeroSorte(int numero) {
        int nSorte = 0;
        Random numeroDaSorte = new Random();
        nSorte = numeroDaSorte.nextInt(100);
        return nSorte;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbSagitario = new javax.swing.JLabel();
        lbCancer = new javax.swing.JLabel();
        lbPeixes = new javax.swing.JLabel();
        lbAquario = new javax.swing.JLabel();
        lbCapricornio = new javax.swing.JLabel();
        lbEscorpiao = new javax.swing.JLabel();
        lbLibra = new javax.swing.JLabel();
        lbVirgem = new javax.swing.JLabel();
        lbLeao = new javax.swing.JLabel();
        lbGemeos = new javax.swing.JLabel();
        lbTouro = new javax.swing.JLabel();
        lbAries = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lbResumo3 = new javax.swing.JLabel();
        lbResumo2 = new javax.swing.JLabel();
        lbResumo1 = new javax.swing.JLabel();
        lbResumo = new javax.swing.JLabel();
        btLimpar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        lbMes = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        lbDia = new javax.swing.JLabel();
        lbAno = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbFem = new javax.swing.JRadioButton();
        rbMasc = new javax.swing.JRadioButton();
        lbNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSagitario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif sagita resized.gif"))); // NOI18N
        getContentPane().add(lbSagitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        lbCancer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/gif Cancer.gif"))); // NOI18N
        getContentPane().add(lbCancer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        lbPeixes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Peixes.gif"))); // NOI18N
        getContentPane().add(lbPeixes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        lbAquario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Aquario.gif"))); // NOI18N
        getContentPane().add(lbAquario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        lbCapricornio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Capricornio.gif"))); // NOI18N
        getContentPane().add(lbCapricornio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        lbEscorpiao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Scorpio.gif"))); // NOI18N
        getContentPane().add(lbEscorpiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        lbLibra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif libra.gif"))); // NOI18N
        getContentPane().add(lbLibra, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        lbVirgem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/gif Virgo.gif"))); // NOI18N
        getContentPane().add(lbVirgem, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        lbLeao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif leo.gif"))); // NOI18N
        getContentPane().add(lbLeao, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        lbGemeos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif gemeos.gif"))); // NOI18N
        getContentPane().add(lbGemeos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        lbTouro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif touro.gif"))); // NOI18N
        getContentPane().add(lbTouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        lbAries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/gif Aries.gif"))); // NOI18N
        getContentPane().add(lbAries, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        txtNome.setText("Insira seu nome e sobrenome");
        txtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 240, -1));

        lbResumo3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbResumo3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbResumo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 380, 30));

        lbResumo2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbResumo2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbResumo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 380, 30));

        lbResumo1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbResumo1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbResumo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 330, 30));

        lbResumo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbResumo.setForeground(new java.awt.Color(255, 255, 255));
        lbResumo.setText("Resumo");
        getContentPane().add(lbResumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 380, 30));

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        lbMes.setForeground(new java.awt.Color(255, 255, 255));
        lbMes.setText("Mês");
        getContentPane().add(lbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        txtAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoActionPerformed(evt);
            }
        });
        txtAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnoKeyTyped(evt);
            }
        });
        getContentPane().add(txtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 70, -1));

        txtDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaActionPerformed(evt);
            }
        });
        txtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiaKeyTyped(evt);
            }
        });
        getContentPane().add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 70, -1));

        txtMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesActionPerformed(evt);
            }
        });
        txtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMesKeyTyped(evt);
            }
        });
        getContentPane().add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 70, -1));

        lbSexo.setForeground(new java.awt.Color(255, 255, 255));
        lbSexo.setText("Sexo");
        getContentPane().add(lbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        lbDia.setForeground(new java.awt.Color(255, 255, 255));
        lbDia.setText("Dia");
        getContentPane().add(lbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        lbAno.setForeground(new java.awt.Color(255, 255, 255));
        lbAno.setText("Ano");
        getContentPane().add(lbAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GURU ON-LINE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 260, 40));

        buttonGroup1.add(rbFem);
        rbFem.setForeground(new java.awt.Color(255, 255, 255));
        rbFem.setText("Feminino");
        getContentPane().add(rbFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        buttonGroup1.add(rbMasc);
        rbMasc.setForeground(new java.awt.Color(255, 255, 255));
        rbMasc.setSelected(true);
        rbMasc.setText("Masculino");
        getContentPane().add(rbMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        lbNome.setForeground(new java.awt.Color(255, 255, 255));
        lbNome.setText("Nome:");
        getContentPane().add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Logo signos Desfocada.jpg"))); // NOI18N
        jLabel1.setText("ffg");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txtNome.setText(null);
        txtAno.setText(null);
        txtDia.setText(null);
        txtMes.setText(null);
        lbResumo.setText("Resumo");
        lbResumo1.setText(null);
        lbResumo2.setText(null);
        lbAries.setIcon(null);
        lbTouro.setIcon(null);
        lbGemeos.setIcon(null);
        lbCancer.setIcon(null);
        lbLeao.setIcon(null);
        lbVirgem.setIcon(null);
        lbLibra.setIcon(null);
        lbEscorpiao.setIcon(null);
        lbSagitario.setIcon(null);
        lbCapricornio.setIcon(null);
        lbAquario.setIcon(null);
        lbPeixes.setIcon(null);
        lbResumo3.setText(null);
        txtNome.setText("Insira seu nome e sobrenome");
        JOptionPane.showMessageDialog(null, "Campos limpos");
    }//GEN-LAST:event_btLimparActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoActionPerformed

    private void txtMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesActionPerformed

    private void txtDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        DecimalFormat d = new DecimalFormat("0");
        String nome, signo, cor;
        int dia, mes, ano;
        cor = "";

        if (txtNome.getText().isEmpty() || txtDia.getText().isEmpty() || txtMes.getText().isEmpty() || txtAno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Muito engraçado, agora preenche os campos vai.");
        } else {
            dia = Integer.parseInt(txtDia.getText());
            mes = Integer.parseInt(txtMes.getText());
            ano = Integer.parseInt(txtAno.getText());

            if (mes >= 1 && mes <= 12 && ano >= 1900 && ano <= 2024) {
                if ((mes == 1 || mes == 3 || mes == 5 || mes == 7 || mes == 8 || mes == 10 || mes == 12) && dia >= 1 && dia <= 31) {
                    nome = txtNome.getText();
                    if (nome.length() < 8 || nome.equals("Insira seu nome e sobrenome")) {
                        JOptionPane.showMessageDialog(null, "Legal, se seu nome fosse verdadeiro.");
                    } else {
                        cor = declararCorDaSorte(cor);
                        signo = calcularSigno(dia, mes, ano);

                        if (rbMasc.isSelected()) {
                            lbResumo.setText(fazerTratamento(nome) + " " + nome + " nascido no dia de " + dia + "/" + mes + "/" + ano);
                            lbResumo1.setText("É do signo de " + signo + " tem " + d.format((calcularIdade(dia, mes, ano))) + " anos");
                            lbResumo2.setText("Seu número da sorte é: " + entregarNumeroSorte(100));
                            lbResumo3.setText("Sua cor da sorte é: " + cor);
                        } else {
                            lbResumo.setText(fazerTratamento(nome) + " " + nome + " nascida no dia de " + dia + "/" + mes + "/" + ano);
                            lbResumo1.setText("É do signo de " + signo + " tem " + d.format((calcularIdade(dia, mes, ano))) + " anos");
                            lbResumo2.setText("Seu número da sorte é: " + entregarNumeroSorte(100));
                            lbResumo3.setText("Sua cor da sorte é: " + cor);
                        }

                        // Definindo os ícones de cada signo.
                        lbSagitario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif sagita resized.gif")));
                        lbAries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/gif Aries.gif")));
                        lbTouro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif touro.gif")));
                        lbCancer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/gif Cancer.gif")));
                        lbGemeos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif gemeos.gif")));
                        lbLeao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif leo.gif")));
                        lbVirgem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/gif Virgo.gif")));
                        lbLibra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif libra.gif")));
                        lbEscorpiao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Scorpio.gif")));
                        lbCapricornio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Capricornio.gif")));
                        lbAquario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Aquario.gif")));
                        lbPeixes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Peixes.gif")));
                        lbAries.setVisible(false);
                        lbTouro.setVisible(false);
                        lbGemeos.setVisible(false);
                        lbCancer.setVisible(false);
                        lbLeao.setVisible(false);
                        lbVirgem.setVisible(false);
                        lbLibra.setVisible(false);
                        lbEscorpiao.setVisible(false);
                        lbSagitario.setVisible(false);
                        lbCapricornio.setVisible(false);
                        lbAquario.setVisible(false);
                        lbPeixes.setVisible(false);

                        if (signo.equals("Aries")) {
                            lbAries.setVisible(true);
                        } else if (signo.equals("Touro")) {
                            lbTouro.setVisible(true);
                        } else if (signo.equals("Gêmeos")) {
                            lbGemeos.setVisible(true);
                        } else if (signo.equals("Câncer")) {
                            lbCancer.setVisible(true);
                        } else if (signo.equals("Leão")) {
                            lbLeao.setVisible(true);
                        } else if (signo.equals("Virgem")) {
                            lbVirgem.setVisible(true);
                        } else if (signo.equals("Libra")) {
                            lbLibra.setVisible(true);
                        } else if (signo.equals("Escorpião")) {
                            lbEscorpiao.setVisible(true);
                        } else if (signo.equals("Sagitário")) {
                            lbSagitario.setVisible(true);
                        } else if (signo.equals("Capricórnio")) {
                            lbCapricornio.setVisible(true);
                        } else if (signo.equals("Aquário")) {
                            lbAquario.setVisible(true);
                        } else if (signo.equals("Peixes")) {
                            lbPeixes.setVisible(true);
                        }
                    }
                } else if ((mes == 4 || mes == 6 || mes == 9 || mes == 11) && dia >= 1 && dia <= 30) {
                    nome = txtNome.getText();
                    if (nome.length() < 8 || nome.equals("Insira seu nome e sobrenome")) {
                        JOptionPane.showMessageDialog(null, "Legal, se seu nome fosse verdadeiro.");
                    } else {
                        cor = declararCorDaSorte(cor);
                        signo = calcularSigno(dia, mes, ano);

                        if (rbMasc.isSelected()) {
                            lbResumo.setText(fazerTratamento(nome) + " " + nome + " nascido no dia de " + dia + "/" + mes + "/" + ano);
                            lbResumo1.setText("É do signo de " + signo + " tem " + d.format((calcularIdade(dia, mes, ano))) + " anos");
                            lbResumo2.setText("Seu número da sorte é: " + entregarNumeroSorte(100));
                            lbResumo3.setText("Sua cor da sorte é: " + cor);
                        } else {
                            lbResumo.setText(fazerTratamento(nome) + " " + nome + " nascida no dia de " + dia + "/" + mes + "/" + ano);
                            lbResumo1.setText("É do signo de " + signo + " tem " + d.format((calcularIdade(dia, mes, ano))) + " anos");
                            lbResumo2.setText("Seu número da sorte é: " + entregarNumeroSorte(100));
                            lbResumo3.setText("Sua cor da sorte é: " + cor);
                        }

                        // Definindo os ícones de cada signo.
                        lbSagitario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif sagita resized.gif")));
                        lbAries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/gif Aries.gif")));
                        lbTouro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif touro.gif")));
                        lbCancer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/gif Cancer.gif")));
                        lbGemeos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif gemeos.gif")));
                        lbLeao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif leo.gif")));
                        lbVirgem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/gif Virgo.gif")));
                        lbLibra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif libra.gif")));
                        lbEscorpiao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Scorpio.gif")));
                        lbCapricornio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Capricornio.gif")));
                        lbAquario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Aquario.gif")));
                        lbPeixes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Peixes.gif")));
                        lbAries.setVisible(false);
                        lbTouro.setVisible(false);
                        lbGemeos.setVisible(false);
                        lbCancer.setVisible(false);
                        lbLeao.setVisible(false);
                        lbVirgem.setVisible(false);
                        lbLibra.setVisible(false);
                        lbEscorpiao.setVisible(false);
                        lbSagitario.setVisible(false);
                        lbCapricornio.setVisible(false);
                        lbAquario.setVisible(false);
                        lbPeixes.setVisible(false);

                        if (signo.equals("Aries")) {
                            lbAries.setVisible(true);
                        } else if (signo.equals("Touro")) {
                            lbTouro.setVisible(true);
                        } else if (signo.equals("Gêmeos")) {
                            lbGemeos.setVisible(true);
                        } else if (signo.equals("Câncer")) {
                            lbCancer.setVisible(true);
                        } else if (signo.equals("Leão")) {
                            lbLeao.setVisible(true);
                        } else if (signo.equals("Virgem")) {
                            lbVirgem.setVisible(true);
                        } else if (signo.equals("Libra")) {
                            lbLibra.setVisible(true);
                        } else if (signo.equals("Escorpião")) {
                            lbEscorpiao.setVisible(true);
                        } else if (signo.equals("Sagitário")) {
                            lbSagitario.setVisible(true);
                        } else if (signo.equals("Capricórnio")) {
                            lbCapricornio.setVisible(true);
                        } else if (signo.equals("Aquário")) {
                            lbAquario.setVisible(true);
                        } else if (signo.equals("Peixes")) {
                            lbPeixes.setVisible(true);
                        }
                    }
                } else if (mes == 2 && dia >= 1 && dia <= 29) {
                    nome = txtNome.getText();
                    if (nome.length() < 8 || nome.equals("Insira seu nome e sobrenome")) {
                        JOptionPane.showMessageDialog(null, "Legal, se seu nome fosse verdadeiro.");
                    } else {
                        cor = declararCorDaSorte(cor);
                        signo = calcularSigno(dia, mes, ano);

                        if (rbMasc.isSelected()) {
                            lbResumo.setText(fazerTratamento(nome) + " " + nome + " nascido no dia de " + dia + "/" + mes + "/" + ano);
                            lbResumo1.setText("É do signo de " + signo + " tem " + d.format((calcularIdade(dia, mes, ano))) + " anos");
                            lbResumo2.setText("Seu número da sorte é: " + entregarNumeroSorte(100));
                            lbResumo3.setText("Sua cor da sorte é: " + cor);
                        } else {
                            lbResumo.setText(fazerTratamento(nome) + " " + nome + " nascida no dia de " + dia + "/" + mes + "/" + ano);
                            lbResumo1.setText("É do signo de " + signo + " tem " + d.format((calcularIdade(dia, mes, ano))) + " anos");
                            lbResumo2.setText("Seu número da sorte é: " + entregarNumeroSorte(100));
                            lbResumo3.setText("Sua cor da sorte é: " + cor);
                        }

                        // Definindo os ícones de cada signo.
                        lbSagitario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif sagita resized.gif")));
                        lbAries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/gif Aries.gif")));
                        lbTouro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif touro.gif")));
                        lbCancer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/gif Cancer.gif")));
                        lbGemeos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif gemeos.gif")));
                        lbLeao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif leo.gif")));
                        lbVirgem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/gif Virgo.gif")));
                        lbLibra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif libra.gif")));
                        lbEscorpiao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Scorpio.gif")));
                        lbCapricornio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Capricornio.gif")));
                        lbAquario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Aquario.gif")));
                        lbPeixes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ulbra/br/view/Gif Peixes.gif")));
                        lbAries.setVisible(false);
                        lbTouro.setVisible(false);
                        lbGemeos.setVisible(false);
                        lbCancer.setVisible(false);
                        lbLeao.setVisible(false);
                        lbVirgem.setVisible(false);
                        lbLibra.setVisible(false);
                        lbEscorpiao.setVisible(false);
                        lbSagitario.setVisible(false);
                        lbCapricornio.setVisible(false);
                        lbAquario.setVisible(false);
                        lbPeixes.setVisible(false);

                        if (signo.equals("Aries")) {
                            lbAries.setVisible(true);
                        } else if (signo.equals("Touro")) {
                            lbTouro.setVisible(true);
                        } else if (signo.equals("Gêmeos")) {
                            lbGemeos.setVisible(true);
                        } else if (signo.equals("Câncer")) {
                            lbCancer.setVisible(true);
                        } else if (signo.equals("Leão")) {
                            lbLeao.setVisible(true);
                        } else if (signo.equals("Virgem")) {
                            lbVirgem.setVisible(true);
                        } else if (signo.equals("Libra")) {
                            lbLibra.setVisible(true);
                        } else if (signo.equals("Escorpião")) {
                            lbEscorpiao.setVisible(true);
                        } else if (signo.equals("Sagitário")) {
                            lbSagitario.setVisible(true);
                        } else if (signo.equals("Capricórnio")) {
                            lbCapricornio.setVisible(true);
                        } else if (signo.equals("Aquário")) {
                            lbAquario.setVisible(true);
                        } else if (signo.equals("Peixes")) {
                            lbPeixes.setVisible(true);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "E essa data ai engraçadinho?");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Po, data legal, marquei de rir daqui 1 semana.");
            }
        }
    }//GEN-LAST:event_btConsultarActionPerformed

    private void txtDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiaKeyTyped
        String caracteres = "QWERTYUIOPASDFGHJKLÇZXCVBNMqwertyuiopasdfghjklçxczvbnm!@#$%¨&*()-_=+§{[ª~^|}]'º:;?/°,.\\\"";
        if (caracteres.contains(evt.getKeyChar() + "")) {
            JOptionPane.showMessageDialog(null, "Apenas números são permitidos");
            evt.consume();
        }

    }//GEN-LAST:event_txtDiaKeyTyped

    private void txtAnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnoKeyTyped
        String caracteres = "QWERTYUIOPASDFGHJKLÇZXCVBNMqwertyuiopasdfghjklçxczvbnm!@#$%¨&*()-_=+§{[ª~^|}]'º:;?/°,.\\\"";
        if (caracteres.contains(evt.getKeyChar() + "")) {
            JOptionPane.showMessageDialog(null, "Apenas números são permitidos");
            evt.consume();
        }
    }//GEN-LAST:event_txtAnoKeyTyped

    private void txtMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesKeyTyped
        String caracteres = "QWERTYUIOPASDFGHJKLÇZXCVBNMqwertyuiopasdfghjklçxczvbnm!@#$%¨&*()-_=+§{[ª~^|}]'º:;?/°,.\\\"";
        if (caracteres.contains(evt.getKeyChar() + "")) {
            JOptionPane.showMessageDialog(null, "Apenas números são permitidos");
            evt.consume();
        }
    }//GEN-LAST:event_txtMesKeyTyped

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        if (txtNome.getText().equals("Insira seu nome e sobrenome")) {
            txtNome.setText("");
        }

    }//GEN-LAST:event_txtNomeFocusGained
    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        if (txtNome.getText().equals("")) {
            txtNome.setText("Insira seu nome e sobrenome");
        }
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        String caracteres ="1234567890!@#$%¨&*()-_=+§{[ª~^|}]'º:;?/°,.\\\"";
        if (caracteres.contains(evt.getKeyChar() + "")) {
            JOptionPane.showMessageDialog(null, "Caracteres especiais não são permitidos.");
            JOptionPane.showMessageDialog(null, "Números também não, então pfv só letras tá? ;)");
            evt.consume();
        }
    }//GEN-LAST:event_txtNomeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignosGabrielEGustavoNoite.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignosGabrielEGustavoNoite.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignosGabrielEGustavoNoite.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignosGabrielEGustavoNoite.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignosGabrielEGustavoNoite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbAno;
    private javax.swing.JLabel lbAquario;
    private javax.swing.JLabel lbAries;
    private javax.swing.JLabel lbCancer;
    private javax.swing.JLabel lbCapricornio;
    private javax.swing.JLabel lbDia;
    private javax.swing.JLabel lbEscorpiao;
    private javax.swing.JLabel lbGemeos;
    private javax.swing.JLabel lbLeao;
    private javax.swing.JLabel lbLibra;
    private javax.swing.JLabel lbMes;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPeixes;
    private javax.swing.JLabel lbResumo;
    private javax.swing.JLabel lbResumo1;
    private javax.swing.JLabel lbResumo2;
    private javax.swing.JLabel lbResumo3;
    private javax.swing.JLabel lbSagitario;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTouro;
    private javax.swing.JLabel lbVirgem;
    private javax.swing.JRadioButton rbFem;
    private javax.swing.JRadioButton rbMasc;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
